### PR TITLE
Raw data fit

### PR DESCRIPTION
**Pull request by CY-dev**
Hi Patrick,

Hope you are doing well. I have built a "ncvreg_raw" function for model fitting on raw data with an option "intercept" for whether or not an intercept should be included. In addition, I have also modified functions for prediction, plot, summary, log likelihood and cross validation to support the model fit returned by ncvreg_raw. I have tested them on prostate data.

Currently, ncvreg_raw only supports family = "gaussian" and support on mfdr, perm, permres are still lacking. If you think the current pull request is satisfactory, I will continue to add all or part of the missing pieces you deem necessary.

Besides, I have found that penalty.factor returned from ncvreg function only has the factors for "nonsingular" columns with std > 1e-6, but it is used in plot.ncvreg as follows:
  YY <- if (length(x$penalty.factor)==nrow(x$beta)) coef(x) else coef(x)[-1,,drop=FALSE]
which seems to be assuming dimension of penalty.factor is the same as X. So I slightly modified the penalty.factor in ncvreg.R. 

Please tell me if you have any questions about the code. Hope you like the raw data addition!

Thanks,
Congrui

### CODE REVIEW

**Comment by pbreheny** [comment]
Hi Congrui,

This looks great!  I just have one comment/question before I merge, though.  It seems to me that `ncvreg_raw` shouldn't screen for singular columns, the way that `ncvreg` does.  The reason for screening is that there's no way to standardize a singular column.  But if we're not standardizing, then it doesn't matter, and I would imagine that a user might want to include their own intercept column in such cases; however, `ncvreg_raw` seems to screen such columns out.  Thoughts?

As for the other options, I don't think `ncvreg_raw` *should* support those things.  I see the main use of `ncvreg_raw` being that a person wants to fit a complex model and that some portion of it can be reduced, via a quadratic approximation, to a least squares optimization.  In such cases, I think that person is on their own for how to carry out inference, etc.

--Patrick

**Comment by CY-dev** [comment]
Hi Patrick, sorry for the late reply. I didn't get any email reminder of your comment and just found out you already responded last year! I have resolved the conflicts and left ncvreg_raw out for mFDR as you suggested. For the singular columns, I prefer to have them removed since including those columns could cause numerical instability inside the coordinate descent implementation.

**Comment by CY-dev** [comment]
Strange thing is, after I clicked the "Resolve conflicts" button and actually resolved the conflicts, the codes still returned to the old conflicted version after a page refresh. Looks like I'm better off making commits directly to my branch.

**Comment by pbreheny** [comment]
This has been replaced / superceded by ncvfit() as of version 3.12.0 a5ac17eb9db4f3bd30265535a3cc3d0f62d23c5a

**Pull request closed without merging**
